apiVersion: apps/v1
kind: Deployment
metadata:
  name: base
  namespace: tk8s
  labels:
    app: base
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: base
        image: krpc:v5
        ports:
        - containerPort: 8886
        - containerPort: 4005
        readinessProbe:
          tcpSocket:
            port: 8886
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8886
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: base-svc
  namespace: tk8s
spec:
  ports:
  - name: http
    port: 8886
    protocol: TCP
    targetPort: 8886
  - name: prometheus
    port: 4005
    protocol: TCP
    targetPort: 4005
  selector:
    app: base

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: base-hpa-c
  namespace: tk8s
  labels:
    app: base-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: base
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: base-hpa-m
  namespace: tk8s
  labels:
    app: base-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: base
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
