
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-slave-1 #mysql-config-slave-0
  namespace: tk8s
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    server-id = 3
    log-bin = mysql-bin
    binlog-format = row
    gtid-mode = on
    enforce-gtid-consistency = true


      
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tk8s
type: Opaque
data:
  mysql-root-password: UFhETjkzVlJLVW04VGVFNw== #根用户密码
  mysql-root-username: cm9vdA==
  mysql-user: cm9vdA== #root
  mysql-password: UFhETjkzVlJLVW04VGVFNw== # PXDN93VRKUm8TeE7

