apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage
provisioner: kubernetes.io/no-provisioner 
volumeBindingMode: WaitForFirstConsumer   # 延迟绑定


---
#pv需要根据需求多建几个
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master  #mysql-pv-slave-1   #mysql-pv-slave-2
  namespace: tk8s 
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data3"
  storageClassName: mysql-storage

